# Generated by Django 6.0.2 on 2026-02-26 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PesticideProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=150)),
                ('license_id', models.CharField(max_length=50)),
                ('since_years', models.PositiveIntegerField(default=0)),
                ('products_sold', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('tractor', 'Tractor Driver'), ('labor', 'Labor'), ('lease', 'Leasehold Land Owner'), ('tools', 'Farming Tools For Rent'), ('pesticide', 'Fertilizer & Pesticide Shop')], max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('mandal', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('mobile', 'role')},
            },
        ),
        migrations.CreateModel(
            name='TractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('wage_amount', models.PositiveIntegerField(default=0)),
                ('driving_license', models.CharField(blank=True, max_length=20, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tractor_details', to='kisan1.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='TractorBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_hours', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tractor_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kisan1.tractorprofile')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tractor_bookings', to='kisan1.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='ToolsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tools_type', models.CharField(blank=True, max_length=200, null=True)),
                ('rent_per_hour', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tools_details', to='kisan1.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='ToolRentalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_selected', models.TextField(help_text='E.g., Tractor: 2 hrs, Harvester: 4 hrs')),
                ('receive_date', models.DateField()),
                ('return_date', models.DateField()),
                ('home_delivery', models.BooleanField(default=False)),
                ('delivery_location', models.CharField(blank=True, max_length=255, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kisan1.toolsprofile')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_bookings', to='kisan1.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_ordered', models.TextField(help_text='E.g., Urea: 2 Bags, Cotton Seed: 5 Pkts')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kisan1.pesticideprofile')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to='kisan1.userregistration')),
            ],
        ),
        migrations.AddField(
            model_name='pesticideprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pesticide_details', to='kisan1.userregistration'),
        ),
        migrations.CreateModel(
            name='PesticideInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('stock_quantity', models.PositiveIntegerField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='kisan1.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('hours', models.PositiveIntegerField(blank=True, null=True)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('farmer_mobile', models.CharField(max_length=10)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_orders', to='kisan1.userregistration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='kisan1.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_land', models.FloatField(default=0.0)),
                ('water_facility', models.CharField(blank=True, max_length=100, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=500, null=True)),
                ('passbook_number', models.CharField(blank=True, max_length=20, null=True)),
                ('lease_per_day', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lease_details', to='kisan1.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseLandRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type_requested', models.CharField(max_length=100)),
                ('duration_months', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('message_to_owner', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kisan1.leaseprofile')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_requests', to='kisan1.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='LaborProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(blank=True, max_length=300, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('wage_amount', models.PositiveIntegerField(default=0)),
                ('wage_type', models.CharField(default='Per Day', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labor_details', to='kisan1.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='LaborBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.PositiveIntegerField(help_text='Number of hours or days')),
                ('location', models.CharField(max_length=255)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laborer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kisan1.laborprofile')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_bookings', to='kisan1.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('passbook_number', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_details', to='kisan1.userregistration')),
            ],
        ),
    ]
