# Generated by Django 5.2.11 on 2026-02-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisan1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6)),
                ('state', models.CharField(default='Telangana', max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('mandal', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
            ],
        ),
    ]
