# Generated by Django 6.0.3 on 2026-03-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kisan1", "0002_pincodemapping"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="laborbooking",
            index=models.Index(
                fields=["status", "created_at"], name="kisan1_labo_status_0505c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaselandrequest",
            index=models.Index(
                fields=["status", "created_at"], name="kisan1_leas_status_e13bb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "created_at"], name="kisan1_orde_status_b19155_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoporder",
            index=models.Index(
                fields=["status", "created_at"], name="kisan1_shop_status_a6cfc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolrentalbooking",
            index=models.Index(
                fields=["status", "created_at"], name="kisan1_tool_status_15be79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tractorbooking",
            index=models.Index(
                fields=["status", "created_at"], name="kisan1_trac_status_a07ee9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userregistration",
            index=models.Index(fields=["role"], name="kisan1_user_role_59d92b_idx"),
        ),
        migrations.AddIndex(
            model_name="userregistration",
            index=models.Index(
                fields=["district"], name="kisan1_user_distric_007fa1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userregistration",
            index=models.Index(
                fields=["created_at"], name="kisan1_user_created_25486d_idx"
            ),
        ),
    ]
