# Generated by Django 6.0.3 on 2026-03-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kisan1", "0003_laborbooking_kisan1_labo_status_0505c9_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "created_at"], name="kisan1_orde_user_id_3d967b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["provider", "created_at"], name="kisan1_orde_provide_9b2e6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pincodemapping",
            index=models.Index(
                fields=["pincode"], name="kisan1_pinc_pincode_17106c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pincodemapping",
            index=models.Index(
                fields=["district", "mandal"], name="kisan1_pinc_distric_53ceea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userregistration",
            index=models.Index(
                fields=["mobile", "role"], name="kisan1_user_mobile_cc442b_idx"
            ),
        ),
    ]
