# Generated by Django 6.0.3 on 2026-03-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kisan1", "0004_order_kisan1_orde_user_id_3d967b_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userregistration",
            name="kisan1_user_mobile_cc442b_idx",
        ),
        migrations.AddIndex(
            model_name="laborbooking",
            index=models.Index(
                fields=["laborer", "booking_date", "start_time", "status"],
                name="kisan1_labo_laborer_646c88_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tractorbooking",
            index=models.Index(
                fields=["tractor_owner", "booking_date", "start_time", "status"],
                name="kisan1_trac_tractor_af82da_idx",
            ),
        ),
    ]
