# Generated by Django 5.2.12 on 2026-03-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisan1', '0006_alter_laborbooking_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userregistration',
            index=models.Index(fields=['mobile', 'role'], name='kisan1_user_mobile_cc442b_idx'),
        ),
    ]
